
# **PARCIAL — Sistemas de ecuaciones lineales (2×2 y 3×3)**

**Duración:** 120 minutos
**Nombre del estudiante:** __________________________
**Curso:** ___________________

---



## **Punto 1 — Método de Igualación (2×2) — 2.0 puntos**

Resuelva el siguiente sistema utilizando **exclusivamente el método de igualación**:

$$
\begin{cases}
3x - 2y = 4 \\
5x + y = 19
\end{cases}
$$

Muestre todos los pasos del procedimiento.

---

## **Punto 2 — Método de Sustitución (2×2) — 2.0 puntos**

Resuelva el siguiente sistema utilizando **exclusivamente el método de sustitución**:

$$
\begin{cases}
2x + 3y = 7 \\
x - 4y = -10
\end{cases}
$$

Explique por qué variable decidió despejar.

---

## **Punto 3 — Método Gráfico (2×2) — 2.0 puntos**

Considere el sistema:

$$
\begin{cases}
y = -2x + 6 \\
y = \tfrac12 x - 3
\end{cases}
$$

1. Grafique ambas rectas en el plano cartesiano.
2. Marque el punto de intersección.
3. Indique si el sistema es consistente e independiente, consistente y dependiente, o inconsistente.

*(El gráfico debe ser a mano).*

---

## **Punto 4 — Determinantes y Regla de Cramer (2×2) — 2.0 puntos**

Utilice determinantes para resolver el sistema (no se acepta otro método):

$$
\begin{cases}
4x + 3y = 1 \\
-2x + y = 5
\end{cases}
$$

Calcule:

* El determinante principal $D$
* $D_x$
* $D_y$
* La solución $(x, y)$

---



## **Punto 5 — Método de Gauss para un sistema 3×3 — 2.0 puntos**

Resuelva por **el método de eliminación de Gauss**, mostrando claramente:


* Transformaciones por ecuaciones
* Forma triangular superior
* Sustitución regresiva

Sistema:

$$
\begin{cases}
x + 2y - z = 4 \\
2x - y + 3z = 1 \\
3x + y + 2z = 10
\end{cases}
$$

Indique claramente la solución única del sistema.




In [3]:
# Sistema:
# x + 2y -  z = 4
# 2x - y + 3z = 1
# 3x + y + 2z = 10

A = [
    [1, 2, -1, 4],
    [2, -1, 3, 1],
    [3, 1, 2, 10]
]

def print_matrix(M):
    for row in M:
        print([round(x, 3) for x in row])
    print()


print("Matriz aumentada inicial:")
print_matrix(A)


Matriz aumentada inicial:
[1, 2, -1, 4]
[2, -1, 3, 1]
[3, 1, 2, 10]



In [4]:

# ======================================================
# Paso 1: Eliminación hacia adelante con pivoteo parcial
# ======================================================

n = 3  # número de ecuaciones

for k in range(n - 1):

    # -------- Pivoteo parcial --------
    # Buscar la fila con el valor absoluto más grande en la columna k
    max_row = max(range(k, n), key=lambda i: abs(A[i][k]))
    
    # Intercambiar filas si es necesario
    if max_row != k:
        A[k], A[max_row] = A[max_row], A[k]
        print(f"Intercambio de F{k+1} con F{max_row+1}:")
        print_matrix(A)

    # -------- Eliminación --------
    for i in range(k + 1, n):
        if A[k][k] == 0:
            raise ValueError("Pivote igual a cero, incluso después de pivoteo.")

        factor = A[i][k] / A[k][k]
        A[i] = [A[i][j] - factor * A[k][j] for j in range(4)]

    print(f"Después de eliminar usando F{k+1}:")
    print_matrix(A)

# ======================================================
# Paso 2: Sustitución hacia atrás
# ======================================================

x = [0] * n

# Resolver z
x[2] = A[2][3] / A[2][2]

# Resolver y
x[1] = (A[1][3] - A[1][2] * x[2]) / A[1][1]

# Resolver x
x[0] = (A[0][3] - A[0][2] * x[2] - A[0][1] * x[1]) / A[0][0]

# ======================================================
# Solución
# ======================================================

print("Solución:")
print(f"x = {x[0]}")
print(f"y = {x[1]}")
print(f"z = {x[2]}")


Intercambio de F1 con F3:
[3, 1, 2, 10]
[2, -1, 3, 1]
[1, 2, -1, 4]

Después de eliminar usando F1:
[3, 1, 2, 10]
[0.0, -1.667, 1.667, -5.667]
[0.0, 1.667, -1.667, 0.667]

Intercambio de F2 con F3:
[3, 1, 2, 10]
[0.0, 1.667, -1.667, 0.667]
[0.0, -1.667, 1.667, -5.667]

Después de eliminar usando F2:
[3, 1, 2, 10]
[0.0, 1.667, -1.667, 0.667]
[0.0, 0.0, 0.0, -5.0]

Solución:
x = 1.1258999068426242e+16
y = -1.1258999068426236e+16
z = -1.1258999068426238e+16


# Empecemos por establecer límites para presentar el parcial. 

# Generación de matrices de coeficientes de entradas primas



In [2]:
import random
import numpy as np

# Lista de números primos menores de 50
primos = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]

# Generar matriz 2x2
matriz_2x2 = np.array([[random.choice(primos) for _ in range(2)] for _ in range(2)])

# Generar matriz 3x3
matriz_3x3 = np.array([[random.choice(primos) for _ in range(3)] for _ in range(3)])

print("Matriz 2x2 con números primos < 50:")
print(matriz_2x2)

print("\nMatriz 3x3 con números primos < 50:")
print(matriz_3x3)


Matriz 2x2 con números primos < 50:
[[23 37]
 [29 11]]

Matriz 3x3 con números primos < 50:
[[ 5 23 17]
 [41  5 29]
 [41 17 41]]
